Repository klaytn/caver-js, pull requests merged in 2019-06, with the labels that each got.

#4 Enable circle-ci
  .circleci/config.yml
  package.json
Labels: closed/fixed, issue/enhancement

#9 Update docs link in readme
  README.md
Labels: issue/bug

#10 Added ./TERMS-OF-USE.md
  TERMS-OF-USE.md
Labels: issue/documentation

#13 Fill zero in front of signature array element before encode
  packages/caver-klay/caver-klay-accounts/src/index.js
  test/packages/caver.klay.accounts.js
Labels: issue/bug, open/approved
