Repository klaytn/caver-js, pull requests merged in 2019-08, with the labels that each got.

#43 Edit docs link with count App tutorial
  README.md
Labels: issue/bug, open/approved

#45 Recommended node version in readme file
  README.md
Labels: issue/enhancement, open/approved

#48 Edit mistypo with tx.type in buildSendRequestFunc
  packages/caver-core-method/src/index.js
  test/contractInstance.js
Labels: issue/bug, open/approved

#49 Add test code for caver.klay.sign
  test/sign.js
Labels: issue/enhancement, open/approved

#52 negate a pattern with dist
  .npmignore
Labels: issue/enhancement, open/approved

#54 Add build steps in job publish
  .circleci/config.yml
Labels: issue/enhancement, open/approved

#56 Combine workflow_publish steps.
  .circleci/config.yml
Labels: closed/fixed, issue/bug, open/approved

#57 TC numbering with test code
  test/decodeTransaction.js
  test/estimateComputationCost.js
  test/eventEmitter.js
  test/getNetworkType.js
  test/getNodeInfo.js
  test/invalidResponse.js
  test/isContractDeployment.js
  test/multiProviderTest.js
  test/personal.js
  test/subscription.js
  test/supportsSubscriptions.js
Labels: issue/enhancement, open/approved

#59 Implemented hex util functions
  packages/caver-utils/src/index.js
  test/packages/caver.klay.utils.js
Labels: issue/enhancement, open/approved

#61 Modify intTest for applying Contract changing
  test/intTest.js
Labels: issue/bug, open/approved

#65 Omit the step of getting information that is not needed when feePayer signs
  packages/caver-klay/caver-klay-accounts/src/index.js
Labels: issue/enhancement, open/approved

#66 Separate serialization test code
  package.json
  test/transactionType/accountCreation.js
  test/transactionType/accountUpdate.js
  test/transactionType/cancelTransaction.js
  test/transactionType/chainDataAnchoring.js
  test/transactionType/contractDeploy.js
  test/transactionType/contractExecution.js
  test/transactionType/feeDelegatedAccountUpdate.js
  test/transactionType/feeDelegatedAccountUpdateWithRatio.js
  test/transactionType/feeDelegatedCancelTransaction.js
  test/transactionType/feeDelegatedCancelTransactionWithRatio.js
  test/transactionType/feeDelegatedContractDeploy.js
  test/transactionType/feeDelegatedContractDeployWithRatio.js
  test/transactionType/feeDelegatedContractExecution.js
  test/transactionType/feeDelegatedContractExecutionWithRatio.js
  test/transactionType/feeDelegatedValueTransfer.js
  test/transactionType/feeDelegatedValueTransferMemo.js
  test/transactionType/feeDelegatedValueTransferMemoWithRatio.js
  test/transactionType/feeDelegatedValueTransferWithRatio.js
  test/transactionType/legacyTransaction.js
  test/transactionType/serializationTest.js
  test/transactionType/valueTransfer.js
  test/transactionType/valueTransferWithMemo.js
Labels: issue/enhancement, open/approved

#67 Add requirements for mocha in readme file
  README.md
Labels: issue/enhancement, open/approved

#63 add header in HttpProvider
  package.json
  test/testHttpHeader.js
Labels: issue/enhancement, open/approved

#68 Add test script in package.json
  package.json
  test/contract.once.js
  test/getNetworkType.js
  test/subscription.js
  test/supportsSubscriptions.js
  test/transactionType/feeDelegatedValueTransferWithRatio.js
Labels: issue/enhancement, open/approved

#69 Fix git repository to klaytn
  test/intTest.js
Labels: issue/enhancement, open/approved

#70 Add integration tx test script to package.json file
  package.json
Labels: issue/enhancement, open/approved

#72 Implement toBuffer, numberToBuffer function in caver.utils
  packages/caver-utils/src/index.js
  test/packages/caver.klay.utils.js
Labels: issue/enhancement, open/approved

#73 [circleci] Add workflow to fit two branches
  .circleci/config.yml
  .circleci/version.sh
Labels: issue/enhancement, open/reviewing

#79 [Master] release/v1.1.1 QA Sign-off
  .circleci/config.yml
  .circleci/version.sh
  package.json
  packages/caver-utils/src/index.js
  test/packages/caver.klay.utils.js
Labels: circleci

#82 Modify xyPointFromPublicKey test code for cover leading zero
  test/packages/caver.klay.utils.js
Labels: open/reviewing

#81 Version upgrade to 1.1.2
  package.json
Labels: open/reviewing

#83 [Master] release/v1.1.2 QA Sign-off
  .circleci/config.yml
  package.json
  test/packages/caver.klay.utils.js
Labels: circleci

#86 caver.utils test case numbering
  package.json
  test/packages/caver.klay.utils.js
Labels: open/reviewing

#84 Add functions to validate transaction hex strings (TPT-596)
  packages/caver-utils/src/index.js
  packages/caver-utils/src/utils.js
  test/packages/caver.klay.utils.js
Labels: issue/enhancement, open/reviewing

#87 Numbering additional test case with caver.utils
  test/packages/caver.klay.utils.js
Labels: open/reviewing
